<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Srunit extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->library('form_validation');
    }

    public function index()
    {
       $this->load->view('tb_srunit_form');
    }

    function add_ajax()
    {
        $count_data = $this->input->post('count_data');
        for($i=1;$i<=$count_data;$i++) {
        
        $NamaObat  = $this->input->post('nama_obat_form['.$i.']');
        $NamaKonversi = $this->input->post('nama_konversi_form['.$i.']');
        $id_srUnit   = $this->input->post('id_srUnit_form['.$i.']');
        $qty_obat   = $this->input->post('qty_obat['.$i.']');

        if($NamaObat != "" and $NamaKonversi != "" and $id_srUnit != "" and $qty_obat != "" ){

            //mencari kode obat berdasarkan nama obat
            //$obat= $this->db->get_where('tb_obat',array('nama_obat'=>$NamaObat))->row_array();
            //mencari kode konversi berdarsakan nama konversi
            //$konversi= $this->db->get_where('tb_konversi',array('nama_konversi'=>$NamaKonversi))->row_array();
            
				echo $NamaObat."<br>";
				echo $NamaKonversi."<br>";
				echo $id_srUnit."<br>";
				echo $qty_obat."<br>";
            }
        } 
        echo $count_data;
 }

}

/* End of file Srunit.php */
/* Location: ./application/controllers/Srunit.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-11-02 10:48:16 */
/* http://harviacode.com */